# Generated by Django 4.0.3 on 2022-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweCourseApp', '0003_topic_learningspace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.RenameField(
            model_name='learningspace',
            old_name='owner',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='learningspace',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='learningspace',
            name='short_description',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
