# Generated by Django 4.0.3 on 2022-04-24 18:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('SweCourseApp', '0005_learningspace_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningspace',
            name='content',
        ),
        migrations.AlterField(
            model_name='learningspace',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
