# Generated by Django 4.0.3 on 2022-04-28 20:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('SweCourseApp', '0006_remove_learningspace_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('duration', models.DateField()),
                ('learning_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweCourseApp.learningspace')),
            ],
        ),
    ]
