# Generated by Django 4.0.3 on 2022-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweCourseApp', '0007_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='duration',
        ),
        migrations.AddField(
            model_name='topic',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated Completion Time(hours)'),
        ),
    ]
