# Generated by Django 4.0.3 on 2022-04-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweCourseApp', '0008_remove_topic_duration_topic_estimated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_topic', to='SweCourseApp.topic')),
                ('prerequisite_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_topic', to='SweCourseApp.topic')),
            ],
        ),
    ]
