# Generated by Django 4.0.3 on 2022-05-18 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SweCourseApp', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
