# Generated by Django 4.0.3 on 2022-05-25 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SweCourseApp', '0014_likedresources_remove_choice_question_delete_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSpaceParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweCourseApp.learningspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
